In [1]:
import pandas as pd
import numpy as np

In [2]:
def rename_column(column: str) -> str:
    return ''.join(char if char.isalnum() else '_' for char in column)\
        .replace('__', '_').rstrip('_')


df = pd.read_csv('dairy_dataset.csv', parse_dates=
                 ['Date', 'Production Date', 'Expiration Date'])
df.rename(columns={column: rename_column(column)
                   for column in df.columns}, inplace=True)
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Total_Land_Area_acres,4325.0,503.483073,10.17,252.95,509.17,751.25,999.53,285.935061
Number_of_Cows,4325.0,54.963699,10.0,32.0,55.0,77.0,100.0,26.111487
Date,4325,2020-12-15 22:59:04.231213824,2019-01-01 00:00:00,2019-12-20 00:00:00,2020-12-02 00:00:00,2021-12-15 00:00:00,2022-12-28 00:00:00,NaN
Product_ID,4325.0,5.509595,1.0,3.0,6.0,8.0,10.0,2.842979
Quantity_liters_kg,4325.0,500.652657,1.17,254.17,497.55,749.78,999.93,288.975915
Price_per_Unit,4325.0,54.785938,10.03,32.46,54.4,77.46,99.99,26.002815
Total_Value,4325.0,27357.845411,42.5165,9946.8145,21869.6529,40954.441,99036.3696,21621.051594
Shelf_Life_days,4325.0,29.12763,1.0,10.0,22.0,30.0,150.0,30.272114
Production_Date,4325,2020-11-15 08:53:22.959537664,2018-11-02 00:00:00,2019-11-23 00:00:00,2020-10-29 00:00:00,2021-11-16 00:00:00,2022-12-22 00:00:00,NaN
Expiration_Date,4325,2020-12-14 11:57:10.196531968,2018-11-14 00:00:00,2019-12-20 00:00:00,2020-11-29 00:00:00,2021-12-13 00:00:00,2023-05-17 00:00:00,NaN
Quantity_Sold_liters_kg,4325.0,248.095029,1.0,69.0,189.0,374.0,960.0,217.024182
Price_per_Unit_sold,4325.0,54.77914,5.21,32.64,54.14,77.46,104.51,26.19279
Approx_Total_Revenue_INR,4325.0,13580.265401,12.54,2916.65,8394.54,19504.55,89108.9,14617.009122
Quantity_in_Stock_liters_kg,4325.0,252.068671,0.0,66.0,191.0,387.0,976.0,223.62087
Minimum_Stock_Threshold_liters_kg,4325.0,55.826143,10.02,32.91,56.46,79.01,99.99,26.30145
Reorder_Quantity_liters_kg,4325.0,109.10782,20.02,64.28,108.34,153.39,199.95,51.501035

In [3]:
all_columns = list(df.columns)

def binarize_catagories(column: str) -> None:
    catagories = df[column].unique()

    features = []
    for catagory in catagories:
        feature = column + '_' + rename_column(catagory)
        df[feature] = df[column] == catagory
        features.append(feature)

    index = all_columns.index(column)
    all_columns[index+1:index+1] = features

for column in df.columns:
    if df[column].dtype is np.dtype('O'):
        binarize_catagories(column)

In [4]:
# Each group of binary features should be exhaustive and mutually exclusive.
# Exhaustive means that at least one of the features is True for each row.
# Mutually exclusive means that only one of the features is True for each row.

for column in df.columns:
    if df[column].dtype is np.dtype('O'):
        features = [column + '_' + rename_column(catagory)
                    for catagory in df[column].unique()]
        assert np.all(np.logical_or.reduce(df[features]))
        assert not np.any(np.logical_and.reduce(df[features]))

In [5]:
# The minimum date among all date columns.
min_date = min(df[column].min() for column in df.columns
               if df[column].dtype == np.dtype('datetime64[ns]'))
quarters = ['Quarter' + str(quarter) for quarter in range(1, 5)]
months = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

def expand_dates(column: str) -> None:
    features = [column + '_' + suffix for suffix in (
        ['Ordinal', 'Year', 'Month', 'Day'] + quarters + months + weekdays)]
    global df
    df = pd.concat([df, pd.DataFrame([[0] * 4 + [False] * (4 + 12 + 7)],
                                     index=df.index, columns=features)], axis=1)

    df[column + '_Ordinal'] = (df[column] - min_date).dt.days
    df[column + '_Year'] = df[column].dt.year
    df[column + '_Month'] = df[column].dt.month
    df[column + '_Day'] = df[column].dt.day

    for quarter in range(1, 5):
        df[column + '_Quarter' + str(quarter)] = \
            df[column].dt.quarter == quarter

    for i, month in enumerate(months):
        df[column + '_' + month] = df[column].dt.month == i + 1

    for i, weekday in enumerate(weekdays):
        df[column + '_' + weekday] = df[column].dt.weekday == i

    index = all_columns.index(column)
    all_columns[index+1:index+1] = features

for column in df.columns:
    if df[column].dtype == np.dtype('datetime64[ns]'):
        expand_dates(column)

In [6]:
# Each group of binary features should be exhaustive and mutually exclusive.
# Exhaustive means that at least one of the features is True for each row.
# Mutually exclusive means that only one of the features is True for each row.

for column in df.columns:
    if df[column].dtype == np.dtype('datetime64[ns]'):
        for group in [quarters, months, weekdays]:
            features = [column + '_' + feature for feature in group]
            assert np.all(np.logical_or.reduce(df[features]))
            assert not np.any(np.logical_and.reduce(df[features]))

In [7]:
df = df[all_columns]
pd.set_option('display.max_rows', None)
df.to_csv('dairy_dataset_extended.csv', index=False)
df.head().T

,0,1,2,3,4
Location,Telangana,Uttar Pradesh,Tamil Nadu,Telangana,Maharashtra
Location_Telangana,True,False,False,True,False
Location_Uttar_Pradesh,False,True,False,False,False
Location_Tamil_Nadu,False,False,True,False,False
Location_Maharashtra,False,False,False,False,True
Location_Karnataka,False,False,False,False,False
Location_Bihar,False,False,False,False,False
Location_West_Bengal,False,False,False,False,False
Location_Madhya_Pradesh,False,False,False,False,False
Location_Chandigarh,False,False,False,False,False
Location_Delhi,False,False,False,False,False
Location_Gujarat,False,False,False,False,False
Location_Kerala,False,False,False,False,False
Location_Jharkhand,False,False,False,False,False
Location_Rajasthan,False,False,False,False,False
Location_Haryana,False,False,False,False,False
Total_Land_Area_acres,310.84,19.19,581.69,908.0,861.95
Number_of_Cows,96,44,24,89,21
Farm_Size,Medium,Large,Medium,Small,Medium
Farm_Size_Medium,True,False,True,False,True
Farm_Size_Large,False,True,False,False,False
Farm_Size_Small,False,False,False,True,False
Date,2022-02-17 00:00:00,2021-12-01 00:00:00,2022-02-28 00:00:00,2019-06-09 00:00:00,2020-12-14 00:00:00
Date_Ordinal,1203,1125,1214,219,773
Date_Year,2022,2021,2022,2019,2020
Date_Month,2,12,2,6,12
Date_Day,17,1,28,9,14
Date_Quarter1,True,False,True,False,False
Date_Quarter2,False,False,False,True,False
Date_Quarter3,False,False,False,False,False
Date_Quarter4,False,True,False,False,True
Date_January,False,False,False,False,False
Date_February,True,False,True,False,False
Date_March,False,False,False,False,False
Date_April,False,False,False,False,False
Date_May,False,False,False,False,False
Date_June,False,False,False,True,False
Date_July,False,False,False,False,False
Date_August,False,False,False,False,False
Date_September,False,False,False,False,False
Date_October,False,False,False,False,False
Date_November,False,False,False,False,False
Date_December,False,True,False,False,True
Date_Monday,False,False,True,False,True
Date_Tuesday,False,False,False,False,False
Date_Wednesday,False,True,False,False,False
Date_Thursday,True,False,False,False,False
Date_Friday,False,False,False,False,False
Date_Saturday,False,False,False,False,False
Date_Sunday,False,False,False,True,False
Product_ID,5,1,4,3,8
Product_Name,Ice Cream,Milk,Yogurt,Cheese,Buttermilk
Product_Name_Ice_Cream,True,False,False,False,False
Product_Name_Milk,False,True,False,False,False
Product_Name_Yogurt,False,False,True,False,False
Product_Name_Cheese,False,False,False,True,False
Product_Name_Buttermilk,False,False,False,False,True
Product_Name_Curd,False,False,False,False,False
Product_Name_Paneer,False,False,False,False,False
Product_Name_Lassi,False,False,False,False,False
Product_Name_Ghee,False,False,False,False,False
Product_Name_Butter,False,False,False,False,False
Brand,Dodla Dairy,Amul,Dodla Dairy,Britannia Industries,Mother Dairy
Brand_Dodla_Dairy,True,False,True,False,False
Brand_Amul,False,True,False,False,False
Brand_Britannia_Industries,False,False,False,True,False
Brand_Mother_Dairy,False,False,False,False,True
Brand_Raj,False,False,False,False,False
Brand_Dynamix_Dairies,False,False,False,False,False
Brand_Sudha,False,False,False,False,False
Brand_Passion_Cheese,False,False,False,False,False
Brand_Warana,False,False,False,False,False
Brand_Palle2patnam,False,False,False,False,False
Brand_Parag_Milk_Foods,False,False,False,False,False
Quantity_liters_kg,222.4,687.48,503.48,823.36,147.77
Price_per_Unit,85.72,42.61,36.5,26.52,83.85
Total_Value,19064.128,29293.5228,18377.02,21835.5072,12390.5145
Shelf_Life_days,25,22,30,72,11
Storage_Condition,Frozen,Tetra Pack,Refrigerated,Frozen,Refrigerated
Storage_Condition_Frozen,True,False,False,True,False
Storage_Condition_Tetra_Pack,False,True,False,False,False
Storage_Condition_Refrigerated,False,False,True,False,True
Storage_Condition_Polythene_Packet,False,False,False,False,False
Storage_Condition_Ambient,False,False,False,False,False
Production_Date,2021-12-27 00:00:00,2021-10-03 00:00:00,2022-01-14 00:00:00,2019-05-15 00:00:00,2020-10-17 00:00:00
Production_Date_Ordinal,1151,1066,1169,194,715
Production_Date_Year,2021,2021,2022,2019,2020
Production_Date_Month,12,10,1,5,10
Production_Date_Day,27,3,14,15,17
Production_Date_Quarter1,False,False,True,False,False
Production_Date_Quarter2,False,False,False,True,False
Production_Date_Quarter3,False,False,False,False,False
Production_Date_Quarter4,True,True,False,False,True
Production_Date_January,False,False,True,False,False
Production_Date_February,False,False,False,False,False
Production_Date_March,False,False,False,False,False
Production_Date_April,False,False,False,False,False
Production_Date_May,False,False,False,True,False
Production_Date_June,False,False,False,False,False
Production_Date_July,False,False,False,False,False
Production_Date_August,False,False,False,False,False
Production_Date_September,False,False,False,False,False
Production_Date_October,False,True,False,False,True
Production_Date_November,False,False,False,False,False
Production_Date_December,True,False,False,False,False
Production_Date_Monday,True,False,False,False,False
Production_Date_Tuesday,False,False,False,False,False
Production_Date_Wednesday,False,False,False,True,False
Production_Date_Thursday,False,False,False,False,False
Production_Date_Friday,False,False,True,False,False
Production_Date_Saturday,False,False,False,False,True
Production_Date_Sunday,False,True,False,False,False
Expiration_Date,2022-01-21 00:00:00,2021-10-25 00:00:00,2022-02-13 00:00:00,2019-07-26 00:00:00,2020-10-28 00:00:00
Expiration_Date_Ordinal,1176,1088,1199,266,726
Expiration_Date_Year,2022,2021,2022,2019,2020
Expiration_Date_Month,1,10,2,7,10
Expiration_Date_Day,21,25,13,26,28
Expiration_Date_Quarter1,True,False,True,False,False
Expiration_Date_Quarter2,False,False,False,False,False
Expiration_Date_Quarter3,False,False,False,True,False
Expiration_Date_Quarter4,False,True,False,False,True
Expiration_Date_January,True,False,False,False,False
Expiration_Date_February,False,False,True,False,False
Expiration_Date_March,False,False,False,False,False
Expiration_Date_April,False,False,False,False,False
Expiration_Date_May,False,False,False,False,False
Expiration_Date_June,False,False,False,False,False
Expiration_Date_July,False,False,False,True,False
Expiration_Date_August,False,False,False,False,False
Expiration_Date_September,False,False,False,False,False
Expiration_Date_October,False,True,False,False,True
Expiration_Date_November,False,False,False,False,False
Expiration_Date_December,False,False,False,False,False
Expiration_Date_Monday,False,True,False,False,False
Expiration_Date_Tuesday,False,False,False,False,False
Expiration_Date_Wednesday,False,False,False,False,True
Expiration_Date_Thursday,False,False,False,False,False
Expiration_Date_Friday,True,False,False,True,False
Expiration_Date_Saturday,False,False,False,False,False
Expiration_Date_Sunday,False,False,True,False,False
Quantity_Sold_liters_kg,7,558,256,601,145
Price_per_Unit_sold,82.24,39.24,33.81,28.92,83.07
Approx_Total_Revenue_INR,575.68,21895.92,8655.36,17380.92,12045.15
Customer_Location,Madhya Pradesh,Kerala,Madhya Pradesh,Rajasthan,Jharkhand
Customer_Location_Madhya_Pradesh,True,False,True,False,False
Customer_Location_Kerala,False,True,False,False,False
Customer_Location_Rajasthan,False,False,False,True,False
Customer_Location_Jharkhand,False,False,False,False,True
Customer_Location_Gujarat,False,False,False,False,False
Customer_Location_Karnataka,False,False,False,False,False
Customer_Location_Haryana,False,False,False,False,False
Customer_Location_Tamil_Nadu,False,False,False,False,False
Customer_Location_West_Bengal,False,False,False,False,False
Customer_Location_Telangana,False,False,False,False,False
Customer_Location_Chandigarh,False,False,False,False,False
Customer_Location_Maharashtra,False,False,False,False,False
Customer_Location_Delhi,False,False,False,False,False
Customer_Location_Bihar,False,False,False,False,False
Customer_Location_Uttar_Pradesh,False,False,False,False,False
Sales_Channel,Wholesale,Wholesale,Online,Online,Retail
Sales_Channel_Wholesale,True,True,False,False,False
Sales_Channel_Online,False,False,True,True,False
Sales_Channel_Retail,False,False,False,False,True
Quantity_in_Stock_liters_kg,215,129,247,222,2
Minimum_Stock_Threshold_liters_kg,19.55,43.17,15.1,74.5,76.02
Reorder_Quantity_liters_kg,64.03,181.1,140.83,57.68,33.4

In [8]:
df.shape

(4325, 166)